import {chromium} from 'playwright-core';
import {mkdir} from 'node:fs/promises';
const base=process.env.QA_BASE||'http://127.0.0.1:4173/';
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const routes=['/','/tobey-maguire','/andrew-garfield','/tom-holland','/aranhaverso','/quadrinhos','/comparativo','/cronologia','/por-tras-da-mascara','/fontes'];
const views=[{name:'mobile360',width:360,height:800},{name:'mobile430',width:430,height:932},{name:'tablet',width:768,height:1024},{name:'desktop',width:1366,height:768},{name:'wide',width:1440,height:900}];
await mkdir('qa/rebuild',{recursive:true});const report=[];
for(const view of views){const context=await browser.newContext({viewport:view});for(const route of routes){const page=await context.newPage();const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));const response=await page.goto(`${base}#${route}`,{waitUntil:'domcontentloaded',timeout:20000});await page.locator('h1').waitFor({state:'visible'});await page.evaluate(async()=>{for(let y=0;y<document.documentElement.scrollHeight;y+=700){scrollTo(0,y);await new Promise(resolve=>setTimeout(resolve,25))}scrollTo(0,0)});await page.waitForTimeout(400);const metrics=await page.evaluate(()=>({h1:document.querySelectorAll('h1').length,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,brokenImages:[...document.images].filter(i=>i.complete&&i.naturalWidth===0).length,images:document.images.length,lang:document.documentElement.lang}));if(['mobile360','desktop'].includes(view.name))await page.screenshot({path:`qa/rebuild/${view.name}-${route==='/'?'home':route.slice(1)}.jpg`,fullPage:true,type:'jpeg',quality:75,timeout:30000});report.push({view:view.name,route,status:response?.status(),...metrics,errors});await page.close()}await context.close()}
await browser.close();const failed=report.filter(r=>r.status!==200||r.h1!==1||r.overflow||r.brokenImages||r.errors.length||r.lang!=='pt-BR');console.log(JSON.stringify({base,checks:report.length,failed,report},null,2));if(failed.length)process.exit(1);
